apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
 name: deploy-baremetal-plan
spec:
 workspaces:
  - name: source
 params:
   - name: plan
     description: plan
     type: string
     default: "lab"
   - name: paramfile
     description: paramfile
     type: string
     default: "lab"
   - name: pullsecret
     description: pullsecret
     type: string
     default: "/root/.kcli/openshift_pull.json"
   - name: launch_steps
     description: launch_steps
     type: string
     default: "true"
   - name: deploy_openshift
     description: deploy_openshift
     type: string
     default: "true"
   - name: version
     description: version
     type: string
     default: "stable"
   - name: tag
     description: tag
     type: string
     default: "4.9"
 steps:
   - name: deploy-baremetal-plan
     image: "quay.io/karmab/kcli:latest"
     env:
       - name: PLAN
         value: $(params.plan)
       - name: PARAMFILE
         value: $(params.paramfile)
       - name: PULLSECRET
         value: $(params.pullsecret)
       - name: LAUNCH_STEPS
         value: $(params.launch_steps)
       - name: DEPLOY_OPENSHIFT
         value: $(params.deploy_openshift)
       - name: VERSION
         value: $(params.version)
       - name: TAG
         value: $(params.tag)
     script: |
      #!/usr/bin/env bash
      cd /workspace/source
      echo kcli create plan --force -f kcli_plan_ztp.yml --paramfile $PARAMFILE -P pullsecret=$PULLSECRET -P launch_steps=$LAUNCH_STEPS -P deploy_openshift=$DEPLOY_OPENSHIFT -P version=$VERSION -P tag=$TAG $PLAN
      kcli create plan --force -f kcli_plan_ztp.yml --paramfile $PARAMFILE -P pullsecret=$PULLSECRET -P launch_steps=$LAUNCH_STEPS -P deploy_openshift=$DEPLOY_OPENSHIFT -P version=$VERSION -P tag=$TAG $PLAN
     volumeMounts:
     - mountPath: /root/.kcli
       name: kcli-config
 volumes:
 - configMap:
     defaultMode: 0700
     name: kcli-config
   name: kcli-config
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: deploy-baremetal-plan
spec:
  description: deploy baremetal plan
  params:
  - name: plan
    type: string
    default: "lab-ipv6-ztp-sno"
  - name: paramfile
    type: string
    default: "lab_ipv6_ztp.yml"
  - name: commit
    type: string
    default: "master"
  - name: pullsecret
    type: string
    default: "/root/.kcli/openshift_pull.json"
  - name: launch_steps
    type: string
    default: "true"
  - name: deploy_openshift
    type: string
    default: "true"
  - name: version
    type: string
    default: "stable"
  - name: tag
    type: string
    default: "4.9"
  workspaces:
  - name: git-source
  tasks:
  - name: clone-repo
    taskRef:
      name: git-clone
      kind: ClusterTask
    workspaces:
    - name: output
      workspace: git-source
    params:
    - name: url
      value: https://github.com/karmab/kcli-openshift4-baremetal
    - name: revision
      value: $(params.commit)
  - name: deploy-baremetal-plan
    taskRef:
      name: deploy-baremetal-plan
    runAfter:
    - clone-repo
    workspaces:
    - name: source
      workspace: git-source
    params:
      - name: plan
        value: $(params.plan)
      - name: paramfile
        value: $(params.paramfile)
      - name: pullsecret
        value: $(params.pullsecret)
      - name: launch_steps
        value: $(params.launch_steps)
      - name: deploy_openshift
        value: $(params.deploy_openshift)
      - name: version
        value: $(params.version)
      - name: tag
        value: $(params.tag)
