name: lab-ipv6-acm-sno 
on:
  workflow_dispatch:
    inputs:
      RUNNER:
        description: 'Runner Name'
        required: true
        default: 'u08'
      CLIENT:
        description: 'Client name'
        required: true
        default: 'local'
      PLAN:
        description: 'Plan Name'
        required: true
        default: lab-ipv6-acm-sno
      PARAMFILE:
        description: 'paramfile'
        required: false
        default: lab_ipv6_acm.yml
      PULLSECRET:
        description: 'pullsecret'
        required: false
        default: /root/openshift_pull.json

env:
 HOME: /root

jobs:
    requirements:
      runs-on: ${{github.event.inputs.RUNNER}}
      steps:
       - uses: actions/checkout@v2
       - run: git pull origin ${GITHUB_REF##*/}
       - name: Install kcli
         run: |
           curl https://raw.githubusercontent.com/karmab/kcli/master/install.sh | bash
           # kcli create pool -p /var/lib/libvirt/images default
           # sudo setfacl -m u:$(id -un):rwx /var/lib/libvirt/images

    deploy-plan:
      needs: requirements
      runs-on: ${{github.event.inputs.RUNNER}}  
      steps:
        - name: Deploy kcli plan
          run: kcli -C ${{github.event.inputs.CLIENT}} create plan --force -f kcli_plan_acm.yml --paramfile ${{github.event.inputs.PARAMFILE}} -P pullsecret='${{github.event.inputs.PULLSECRET}}' ${{github.event.inputs.PLAN}} -k
