name: lab-ipv6-acm-sno 
on:
  workflow_dispatch:
    inputs:
      RUNNER:
        description: 'Runner Name'
        required: true
        default: 'u08'
      CLIENT:
        description: 'Client name'
        required: true
        default: 'local'
      PLAN:
        description: 'Plan Name'
        required: true
        default: lab-ipv6-acm-sno
      PARAMFILE:
        description: 'paramfile'
        required: false
        default: lab_ipv6_acm.yml
      ACM_SNAPSHOT:
        description: 'acm_snapshot'
        required: false
        default: 2.3.0-DOWNSTREAM-2021-06-29-05-03-27
      ACM_OP_BUNDLE:
        description: 'acm_op_bundle'
        required: false
        default: v2.3.0-143
      ACM_PULLSECRET:
        description: 'acm_pullsecret'
        required: false
        default: /root/openshift_pull_acm.json
      PULLSECRET:
        description: 'pullsecret'
        required: false
        default: /root/openshift_pull.json

env:
 HOME: /root

jobs:
    requirements:
      runs-on: ${{github.event.inputs.RUNNER}}
      steps:
       - uses: actions/checkout@v2
       - run: git pull origin ${GITHUB_REF##*/}
       - name: Install kcli
         run: |
           curl https://raw.githubusercontent.com/karmab/kcli/master/install.sh | bash
           # kcli create pool -p /var/lib/libvirt/images default
           # sudo setfacl -m u:$(id -un):rwx /var/lib/libvirt/images

    deploy-plan:
      needs: requirements
      runs-on: ${{github.event.inputs.RUNNER}}  
      steps:
        - name: Deploy kcli plan
          run: kcli -C ${{github.event.inputs.CLIENT}} create plan --force -f kcli_plan.yml --paramfile ${{github.event.inputs.PARAMFILE}} -P acm_snapshot='${{github.event.inputs.ACM_SNAPSHOT}}' -P acm_op_bundle='${{github.event.inputs.ACM_OP_BUNDLE}}' -P acm_pullsecret='${{github.event.inputs.ACM_PULLSECRET}}' -P pullsecret='${{github.event.inputs.PULLSECRET}}' ${{github.event.inputs.PLAN}}
