name: lab-without-installer
on:
  workflow_dispatch:
    inputs:
      RUNNER:
        description: 'Runner Name'
        required: true
        default: 'u08'
      PLAN:
        description: 'Plan Name'
        required: true
        default: lab
      INFRAPARAMFILE:
        description: 'infraparamfile'
        required: false
        default: paramfiles/lab.yml
      PARAMFILE:
        description: 'paramfile'
        required: false
        default: paramfiles/lab_without_installer.yml
      PULLSECRET:
        description: 'pullsecret'
        required: false
        default: /root/openshift_pull.json
      VERSION:
        description: 'version'
        required: false
        default: stable
      TAG:
        description: 'tag'
        required: false
        default: "4.10"

env:
 HOME: /root
 PYTHONUNBUFFERED: true

jobs:
    requirements:
      runs-on:  ${{github.event.inputs.RUNNER}} 
      steps:
       - uses: actions/checkout@v2
       - run: git pull origin ${GITHUB_REF##*/}
       - name: Install kcli
         run: |
           curl https://raw.githubusercontent.com/karmab/kcli/master/install.sh | bash
           # kcli create pool -p /var/lib/libvirt/images default
           # sudo setfacl -m u:$(id -un):rwx /var/lib/libvirt/images

    deploy-infra-plan:
      needs: requirements
      runs-on:  ${{github.event.inputs.RUNNER}}   
      steps:
       - name: Deploy infra
         run: kcli create plan --force -f kcli_plan_infra.yml --paramfile ${{github.event.inputs.INFRAPARAMFILE}} ${{github.event.inputs.PLAN}}

    install-redfish:
      needs: deploy-infra-plan
      runs-on:  ${{github.event.inputs.RUNNER}}   
      steps:
       - name: Render sushy
         run: kcli render -f helpers/sushy.conf --paramfile ${{github.event.inputs.INFRAPARAMFILE}} > /etc/sushy.conf
       - name: Install redfish
         run: |
           pip3 install sushy-tools
           cp -f helpers/sushy.service /usr/lib/systemd/system
           ### temp hack ###
           sed -i 's@8000@80@' /etc/sushy.conf
           systemctl restart sushy
           #################
           # systemctl enable --now sushy

    render-redfish-in-parameter-file:
      needs: install-redfish
      runs-on:  ${{github.event.inputs.RUNNER}}   
      steps:
       - name: Render redfish in parameter file
         run: kcli render -f virtual_platform_hosts.yml --paramfile ${{github.event.inputs.INFRAPARAMFILE}} --paramfile ${{github.event.inputs.PARAMFILE}} >> ${{github.event.inputs.PARAMFILE}}

    deploy-cluster:
      needs: render-redfish-in-parameter-file
      runs-on:  ${{github.event.inputs.RUNNER}}   
      steps:
       - name: Deploy cluster
         run: |
           ### temp hack ###
           sed -i 's@:8000@:80@' ${{github.event.inputs.PARAMFILE}}
           #################
           kcli --debug create cluster openshift --paramfile ${{github.event.inputs.PARAMFILE}} -P pull_secret='${{github.event.inputs.PULLSECRET}}' ${{github.event.inputs.PLAN}}-cluster --force
